@isTest
public class PDFtoVFGenerator_Test 
{
	public static testmethod void testGeneration()
    {
        /*PDF__c pdf = new PDF__c(name='TestyBoi',  VFPageId__c='123456789987654321');
        insert pdf;
        
        PDFPage__c pdfPage = new PDFPage__c(name='TestyBoiPage', PDF__c = pdf.id, Page_Number__c = 1);
        insert pdfPage;
        
        PDFPageElement__c pdfPageElement = new PDFPageElement__c(name='TestyBoiElement', 
                                                                 PDFPage__c = pdfPage.id, 
                                                                 Image_URL__c='www.google.com');
        insert pdfPageElement;
        Test.setMock(HttpCalloutMock.class, new PDFtoVFGeneratorMockHTTP_Test());
		PDFtoVFGenerator.VFToolingManager(pdf.id);*/
    }
}