/* PDFPageCSS */

.pdfContainer
{
    background-color: rgb(211,211,211);
}

.pageContainer
{
    display : block;
}

.page
{
    height:620px;
    width:50%;
    margin: auto;
    margin-bottom:10px;
    /*shadowAdd*/ display:table;
}

.pageElement
{
    height:100%;
    display:table-cell;
    vertical-align:middle;
    text-align:center;
    font-size: 12px;
    font-family:courier;
    color: #000000;
    text-align: Center;
}